const ROOT='cloud://cloudbase-d4g93f0re5f3274c1.636c-cloudbase-d4g93f0re5f3274c1-1446269281/ui-assets/assets/';
const C=ROOT+'common/campus-manager/';
const T=ROOT+'pages/team/';
const LEAVE_DETAILS={
  'leave-linhao':{id:'leave-linhao',name:'林浩',classInfo:'U10提高班',type:'病假',date:'7月16日（周二）18:30-20:00',remaining:'2课时',reason:'发烧咳嗽，医生建议休息。',avatar:T+'avatar-linhao.png'},
  'leave-wang':{id:'leave-wang',name:'王子轩',classInfo:'U8启蒙班',type:'事假',date:'7月17日（周三）17:00-18:00',remaining:'1课时',reason:'家庭出行。',avatar:T+'avatar-zhangzixuan.png'},
  'leave-zhang':{id:'leave-zhang',name:'张可欣',classInfo:'U12精英班',type:'病假',date:'7月14日（周日）19:00-20:30',remaining:'2课时',reason:'感冒咳嗽。',avatar:T+'avatar-liuyuchen.png'},
  'leave-li':{id:'leave-li',name:'李明远',classInfo:'U10提高班',type:'病假',date:'7月13日（周六）17:30-19:00',remaining:'1课时',reason:'肠胃不适。',avatar:T+'avatar-liaoran.png'}
};
function actions(active){return[{key:'approve',icon:'✓',title:'通过',note:'审核通过并安排补课'},{key:'supplement',icon:'补',title:'补充材料',note:'通知家长补充证明'},{key:'reject',icon:'×',title:'驳回',note:'不符合请假补课规则'}].map(item=>Object.assign({},item,{activeClass:item.key===active?'active':''}))}
Page({data:{navTop:20,navHeight:44,navSpacer:76,application:LEAVE_DETAILS['leave-linhao'],avatar:T+'avatar-linhao.png',selected:'approve',actions:actions('approve'),remark:'',checks:[{label:'请假时限',value:'提前 22 小时申请',result:'符合规则'},{label:'请假时长',value:'不超过3课时/次',result:'符合规则'},{label:'证明材料',value:'已上传证明',result:'符合规则'},{label:'本周请假次数',value:'本周第 1 次',result:'符合规则'}],icons:{back:C+'icon-back-white-256.png',calendar:C+'icon-calendar-orange-256.png',clock:C+'icon-clock-orange-256.png',check:C+'icon-check-orange-256.png'}},onLoad(options){let t=20,h=44;try{const m=wx.getMenuButtonBoundingClientRect&&wx.getMenuButtonBoundingClientRect();if(m&&m.top){t=m.top;h=m.height||32}else t=wx.getSystemInfoSync().statusBarHeight||20}catch(e){console.warn('[leave-review] nav',e)}const id=options&&LEAVE_DETAILS[options.id]?options.id:'leave-linhao';const application=LEAVE_DETAILS[id];this.setData({navTop:t,navHeight:h,navSpacer:t+h+13,application,avatar:application.avatar})},goBack(){if(getCurrentPages().length>1){wx.navigateBack({delta:1});return}wx.redirectTo({url:'/pages/campus-manager/leave/index',fail:()=>wx.reLaunch({url:'/pages/campus-manager/home/index'})})},selectAction(e){const key=e.currentTarget.dataset.key;this.setData({selected:key,actions:actions(key)})},inputRemark(e){this.setData({remark:e.detail.value||''})},submit(){if(this.data.selected==='reject'){wx.navigateTo({url:'/pages/campus-manager/review-reject/index?id='+this.data.application.id});return}if(this.data.selected==='approve'){wx.navigateTo({url:'/pages/campus-manager/makeup-confirm/index?id='+this.data.application.id});return}wx.showToast({title:'补充材料通知已发送',icon:'success'})},reject(){wx.navigateTo({url:'/pages/campus-manager/review-reject/index?id='+this.data.application.id})}});
