const ROOT='cloud://cloudbase-d4g93f0re5f3274c1.636c-cloudbase-d4g93f0re5f3274c1-1446269281/ui-assets/assets/';
const C=ROOT+'common/campus-manager/';
const T=ROOT+'pages/team/';
const PACKAGE_DETAILS={
  'package-u8':{id:'package-u8',name:'U8启蒙成长包',price:'¥2,680',hours:'48课时',valid:'180天',classInfo:'U8启蒙班',buyers:'126人',status:'在售'},
  'package-u10':{id:'package-u10',name:'U10技能提升包',price:'¥3,980',hours:'72课时',valid:'365天',classInfo:'U10基础班',buyers:'98人',status:'在售'},
  'package-1v1':{id:'package-1v1',name:'1对1专项训练包',price:'¥2,280',hours:'24课时',valid:'120天',classInfo:'1对1专项',buyers:'35人',status:'在售'}
};
Page({data:{navTop:20,navHeight:44,navSpacer:76,packageInfo:PACKAGE_DETAILS['package-u8'],cover:T+'avatar-linhao.png',icons:{back:C+'icon-back-white-256.png',calendar:C+'icon-calendar-orange-256.png',clock:C+'icon-clock-orange-256.png',user:C+'icon-user-orange-256.png',check:C+'icon-check-orange-256.png'},purchases:[{name:'张子轩',date:'2025-07-16 10:30',price:'¥3980',expires:'2026-07-15',avatar:T+'avatar-linhao.png'},{name:'李明远',date:'2025-07-15 18:20',price:'¥3980',expires:'2026-07-14',avatar:T+'avatar-liuyuchen.png'},{name:'王思涵',date:'2025-07-14 16:45',price:'¥3980',expires:'2026-07-13',avatar:T+'avatar-zhangzixuan.png'}]},onLoad(options){let t=20,h=44;try{const m=wx.getMenuButtonBoundingClientRect&&wx.getMenuButtonBoundingClientRect();if(m&&m.top){t=m.top;h=m.height||32}else t=wx.getSystemInfoSync().statusBarHeight||20}catch(e){console.warn('[package-detail] nav',e)}const id=options&&PACKAGE_DETAILS[options.id]?options.id:'package-u8';this.setData({navTop:t,navHeight:h,navSpacer:t+h+14,packageInfo:PACKAGE_DETAILS[id]})},goBack(){if(getCurrentPages().length>1){wx.navigateBack({delta:1});return}wx.redirectTo({url:'/pages/campus-manager/packages/index',fail:()=>wx.reLaunch({url:'/pages/campus-manager/home/index'})})},edit(){wx.navigateTo({url:'/pages/campus-manager/package-edit/index?mode=edit&id='+this.data.packageInfo.id})},changeStatus(){wx.navigateTo({url:'/pages/campus-manager/package-status-confirm/index?action=off&id='+this.data.packageInfo.id})},showStudents(){wx.navigateTo({url:'/pages/campus-manager/students/index?package='+this.data.packageInfo.id})},showToast(e){wx.showToast({title:e.currentTarget.dataset.message||'功能详情',icon:'none'})}});
