const CLOUD_ROOT='cloud://cloudbase-d4g93f0re5f3274c1.636c-cloudbase-d4g93f0re5f3274c1-1446269281/ui-assets/assets/';
const COMMON_ROOT=CLOUD_ROOT+'common/campus-manager/';
const COURSE_DETAILS={
  'course-0900':{id:'course-0900',badge:'U8启蒙班',title:'U8篮球启蒙班',date:'2026.07.19 周日',time:'09:00–10:30',campus:'浦东校区',venue:'1号馆',coach:'王教练',planned:'16',actual:'15',attendance:'94',type:'启蒙训练',age:'7–8岁',level:'U8'},
  'course-1045':{id:'course-1045',badge:'U12进阶班',title:'U12进阶训练班',date:'2026.07.19 周日',time:'10:45–12:15',campus:'浦东校区',venue:'2号馆',coach:'李教练',planned:'18',actual:'17',attendance:'94',type:'进阶训练',age:'11–12岁',level:'U12'},
  'course-1330':{id:'course-1330',badge:'成人基础班',title:'成人篮球基础班',date:'2026.07.19 周日',time:'13:30–15:00',campus:'浦东校区',venue:'3号馆',coach:'张教练',planned:'14',actual:'12',attendance:'86',type:'成人基础',age:'18岁以上',level:'成人'},
  'course-1515':{id:'course-1515',badge:'U8启蒙班',title:'U8篮球启蒙班',date:'2026.07.19 周日',time:'15:15–16:45',campus:'浦东校区',venue:'1号馆',coach:'王教练',planned:'16',actual:'14',attendance:'88',type:'启蒙训练',age:'7–8岁',level:'U8'},
  'course-1700':{id:'course-1700',badge:'U12进阶班',title:'U12进阶训练班',date:'2026.07.19 周日',time:'17:00–18:30',campus:'浦东校区',venue:'2号馆',coach:'李教练',planned:'18',actual:'16',attendance:'89',type:'进阶训练',age:'11–12岁',level:'U12'}
};
Page({data:{navTop:20,navHeight:44,navSpacer:76,course:COURSE_DETAILS['course-0900'],avatar:CLOUD_ROOT+'pages/team/avatar-zhaozimo.png',icons:{back:COMMON_ROOT+'icon-back-orange-256.png'},info:[],changes:[{title:'内容调整',tag:'教练发起',detail:'原计划：投篮训练 → 调整为：运球训练',time:'07.16 13:20'},{title:'时间调整',tag:'教练发起',detail:'原时间：15:30–17:00 → 调整为：14:00–15:30',time:'07.15 18:05'},{title:'学员请假',tag:'家长申请',detail:'学员：张同学（因病请假）',time:'07.16 08:30'}]},onLoad(options){let navTop=20,navHeight=44;try{const menu=wx.getMenuButtonBoundingClientRect&&wx.getMenuButtonBoundingClientRect();if(menu&&menu.top){navTop=menu.top;navHeight=menu.height||32}else{navTop=wx.getSystemInfoSync().statusBarHeight||20}}catch(error){console.warn('[campus-manager-course-detail] nav metrics unavailable',error)}const id=options&&COURSE_DETAILS[options.id]?options.id:'course-0900';const course=COURSE_DETAILS[id];this.setData({navTop,navHeight,navSpacer:navTop+navHeight+16,course,info:[{label:'课程类型',value:course.type,symbol:'课'},{label:'适合年龄',value:course.age,symbol:'龄'},{label:'课程时长',value:'90分钟',symbol:'时'},{label:'课程级别',value:course.level,symbol:'级'}]})},goBack(){if(getCurrentPages().length>1){wx.navigateBack({delta:1});return}wx.redirectTo({url:'/pages/campus-manager/courses/index',fail:()=>wx.reLaunch({url:'/pages/campus-manager/home/index'})})},attendance(){wx.navigateTo({url:'/pages/campus-manager/attendance-detail/index?id='+this.data.course.id})},change(){wx.navigateTo({url:'/pages/campus-manager/course-change/index?id='+this.data.course.id})},cancel(){wx.navigateTo({url:'/pages/campus-manager/cancel-confirm/index?id='+this.data.course.id})}});
