const ROOT='cloud://cloudbase-d4g93f0re5f3274c1.636c-cloudbase-d4g93f0re5f3274c1-1446269281/ui-assets/assets/';
const C=ROOT+'common/campus-manager/';
const T=ROOT+'pages/team/';
const MAKEUP_DETAILS={
  'leave-linhao':{id:'leave-linhao',name:'林浩',classInfo:'U10提高班',leaveType:'病假',leaveDate:'7月16日（周二）18:30',reason:'发烧咳嗽，医生建议休息',coach:'陈教练（主教练）',makeupDate:'7月20日（周六）18:00-19:30',place:'浦东体育中心馆 一号馆A场',seat:'6 / 12 人',avatar:T+'avatar-linhao.png'},
  'leave-wang':{id:'leave-wang',name:'王子轩',classInfo:'U8启蒙班',leaveType:'事假',leaveDate:'7月17日（周三）17:00',reason:'家庭出行',coach:'王教练（主教练）',makeupDate:'7月19日（周五）17:00-18:00',place:'金桥篮球馆 一号场',seat:'5 / 10 人',avatar:T+'avatar-zhangzixuan.png'},
  'makeup-u10':{id:'makeup-u10',name:'待安排学员',classInfo:'U10提高班',leaveType:'已审核请假',leaveDate:'原课程待确认',reason:'从补课推荐进入',coach:'李教练（主教练）',makeupDate:'7月20日（周日）18:00-19:30',place:'浦东体育中心馆',seat:'6 / 12 人',avatar:T+'avatar-linhao.png'},
  'makeup-u8':{id:'makeup-u8',name:'待安排学员',classInfo:'U8启蒙班',leaveType:'已审核请假',leaveDate:'原课程待确认',reason:'从补课推荐进入',coach:'王教练（主教练）',makeupDate:'7月19日（周六）17:00-18:00',place:'金桥篮球馆',seat:'5 / 10 人',avatar:T+'avatar-zhangzixuan.png'}
};
Page({data:{navTop:20,navHeight:44,navSpacer:76,detail:MAKEUP_DETAILS['leave-linhao'],avatar:T+'avatar-linhao.png',notifyParent:true,notifyCoach:true,updateSchedule:true,icons:{back:C+'icon-back-white-256.png',calendar:C+'icon-calendar-orange-256.png',location:C+'icon-location-orange-256.png',clock:C+'icon-clock-orange-256.png'}},onLoad(options){let t=20,h=44;try{const m=wx.getMenuButtonBoundingClientRect&&wx.getMenuButtonBoundingClientRect();if(m&&m.top){t=m.top;h=m.height||32}else t=wx.getSystemInfoSync().statusBarHeight||20}catch(e){console.warn('[makeup-confirm] nav',e)}const id=options&&MAKEUP_DETAILS[options.id]?options.id:'leave-linhao';const detail=MAKEUP_DETAILS[id];this.setData({navTop:t,navHeight:h,navSpacer:t+h+13,detail,avatar:detail.avatar})},goBack(){if(getCurrentPages().length>1){wx.navigateBack({delta:1});return}wx.redirectTo({url:'/pages/campus-manager/leave/index',fail:()=>wx.reLaunch({url:'/pages/campus-manager/home/index'})})},toggle(e){this.setData({[e.currentTarget.dataset.key]:e.detail.value})},reselect(){wx.navigateTo({url:'/pages/campus-manager/substitute-coach/index?mode=makeup&id='+this.data.detail.id})},confirm(){wx.navigateTo({url:'/pages/campus-manager/makeup-result/index?id='+this.data.detail.id})}});
