const ROOT='cloud://cloudbase-d4g93f0re5f3274c1.636c-cloudbase-d4g93f0re5f3274c1-1446269281/ui-assets/assets/pages/team/';
const baseStudents=[
  {id:'s1',name:'林浩',number:'23',package:'剩余18课时',avatar:ROOT+'avatar-linhao.png',status:'present'},
  {id:'s2',name:'刘宇辰',number:'8',package:'剩余6课时',avatar:ROOT+'avatar-liuyuchen.png',status:'leave'},
  {id:'s3',name:'张子轩',number:'11',package:'剩余12课时',avatar:ROOT+'avatar-zhangzixuan.png',status:'makeup'},
  {id:'s4',name:'赵子墨',number:'5',package:'剩余23课时',avatar:ROOT+'avatar-zhaozimo.png',status:'present'},
  {id:'s5',name:'廖然',number:'17',package:'剩余9课时',avatar:ROOT+'avatar-liaoran.png',status:'absent'}
];
function decorate(students){const labels={present:'到课',leave:'请假',absent:'缺勤',makeup:'补课',trial:'试听'};return students.map(item=>({...item,statusLabel:labels[item.status],presentClass:item.status==='present'?'selected':'',leaveClass:item.status==='leave'?'selected':'',absentClass:item.status==='absent'?'selected':'',makeupClass:item.status==='makeup'?'selected':''}))}
Page({data:{students:decorate(baseStudents),presentCount:2,leaveCount:1,absentCount:1,makeupCount:1,consumeCount:3},onStatus(e){const id=e.currentTarget.dataset.id,status=e.currentTarget.dataset.status;const students=this.data.students.map(item=>item.id===id?{...item,status}:item);this.sync(students)},markAll(){this.sync(this.data.students.map(item=>({...item,status:'present'})))},sync(students){const decorated=decorate(students);this.setData({students:decorated,presentCount:decorated.filter(i=>i.status==='present').length,leaveCount:decorated.filter(i=>i.status==='leave').length,absentCount:decorated.filter(i=>i.status==='absent').length,makeupCount:decorated.filter(i=>i.status==='makeup').length,consumeCount:decorated.filter(i=>i.status==='present'||i.status==='makeup').length})},goBack(){const pages=getCurrentPages();if(pages.length>1){wx.navigateBack({delta:1});return}wx.redirectTo({url:'/pages/coach-course-detail/index?id=course-2'})},confirm(){wx.showModal({title:'确认点名并开始上课',content:'将保存本节课出勤结果并进入上课流程。课后评价会在本节课完成后统一生成待办。',success:r=>{if(!r.confirm)return;const attendees=this.data.students.filter(item=>item.status==='present'||item.status==='makeup').map(item=>({id:item.id,name:item.name,number:item.number,avatar:item.avatar,attendanceStatus:item.status}));wx.setStorageSync('sxf_attendance_course-2',attendees);wx.removeStorageSync('sxf_evaluation_status_course-2');wx.showToast({title:'点名已确认',icon:'success'});setTimeout(()=>wx.navigateTo({url:'/pages/coach-classroom/index?id=course-2'}),500)}})}});
